Updated eslint and prettierx
Intergiro/model-base pull request #52
Opened 2021-09-18 10:22 UTC by robinnedergard

2021-09-20 15:52 UTC, Magnus93 approved these changes

2021-09-20 16:08 UTC, Magnus93 requested changes
Add `"EditorConfig.EditorConfig"` in file `.vscode/extentions.json` to `recomendations`

2021-09-21 07:26 UTC, marcushanses approved these changes

2021-09-21 09:49 UTC, nilssonemma approved these changes

2021-09-22 21:52 UTC, fredrikbryntesson approved these changes

2021-09-22 21:52 UTC, merged